city                  // 市
county                // 所属区域
adminRegion           // 行政区域
organization          // 组织
siteName              // 站址名称
siteNum               // 站址编码
siteType              // 站址类型
longitude             // 经度
latitude              // 纬度
address               // 所在地址
siteTopography        // 站址地形
accessDate            // 入网日期
originalPropertyUnit  // 原产权单位
oneLevelStatus        // 站址一级状态
twoLevelStatus        // 站址二级状态
remark                // 备注
changeTime            // 修改时间
entryStaff            // 录入人员
entryTime             // 录入时间
modifyMan             // 修改人
isBlock               // 是否封锁
siteSource            // 站址来源
sourceIndustry        // 来源行业
sourceChannel         // 来源渠道
siteMergeRecord       // 站址合并记录
siteAcceptFlag        // 站址接收标记
deleteTime            // 删除时间
mobileSiteName        // 原移动站址名
unicomSiteName        // 原联通站址名
telecomSiteName       // 原电信站址名
isTransferTower       // 是否交塔
isTransferRoom        // 是否交房
logOutReason          // 注销原因
anchorBusiness        // 锚定业务
oneLevelBusiness      // 一级业务场景
twoLevelBusiness      // 二级业务场景
businessType          // 业务类型
businessSubclass      // 业务子类
sharedUnit            // 共享单位
baseStationCategory   // 基站类别
actualDemolitionDate  // 实际拆除日期
currentSiteState      // 四库状态
sysDate               // 系统日期

{
    "list": [{
        "city": "杭州市",
        "county": "上城区",
        "adminRegion": "杭州市",
        "organization": "中国铁塔股份有限公司杭州市分公司",
        "siteName": "杭州国际小水电",
        "siteNum": "330106908000000219",
        "siteType": "楼面站",
        "longitude": 120.149931,
        "latitude": 30.231251,
        "address": "浙江省杭州市上城区南山路136号",
        "siteTopography": "平原",
        "accessDate": "2014-12-31T16:00:00.000Z",
        "originalPropertyUnit": "联通",
        "oneLevelStatus": "在网",
        "twoLevelStatus": "正常起租",
        "remark": "上站有难度,grade",
        "changeTime": "2020-04-20T15:54:08.000Z",
        "entryStaff": "adminres",
        "entryTime": "2015-03-11T16:00:00.000Z",
        "modifyMan": "luoyi",
        "isBlock": "否",
        "siteSource": "自有站",
        "sourceIndustry": "通信",
        "sourceChannel": "移交",
        "siteMergeRecord": null,
        "siteAcceptFlag": "虚拟站址",
        "deleteTime": null,
        "mobileSiteName": null,
        "unicomSiteName": "杭州国际小水电",
        "telecomSiteName": null,
        "isTransferTower": "否",
        "isTransferRoom": "否",
        "logOutReason": null,
        "anchorBusiness": "运营商业务类",
        "oneLevelBusiness": "景区",
        "twoLevelBusiness": "3A级景区",
        "businessType": "运营商业务类",
        "businessSubclass": "宏站类",
        "sharedUnit": "联通",
        "baseStationCategory": null,
        "actualDemolitionDate": null,
        "currentSiteState": "正常",
        "sysDate": "2022-08-19T07:55:26.000Z"
    },
    {
        "city": "杭州市",
        "county": "上城区",
        "adminRegion": "杭州市",
        "organization": "中国铁塔股份有限公司杭州市分公司",
        "siteName": "杭州涌金广场",
        "siteNum": "330106908000000234",
        "siteType": "楼面站",
        "longitude": 120.158813,
        "latitude": 30.248741,
        "address": "杭州市上城区延安路139号杭州涌金广场基站",
        "siteTopography": "平原",
        "accessDate": "2014-12-31T16:00:00.000Z",
        "originalPropertyUnit": "联通",
        "oneLevelStatus": "在网",
        "twoLevelStatus": "正常起租",
        "remark": "7e6b4d6f159111e59893fa163e7246ea,grade",
        "changeTime": "2020-04-20T15:54:05.000Z",
        "entryStaff": "adminres",
        "entryTime": "2015-03-11T16:00:00.000Z",
        "modifyMan": "luoyi",
        "isBlock": "否",
        "siteSource": "自有站",
        "sourceIndustry": "通信",
        "sourceChannel": "移交",
        "siteMergeRecord": null,
        "siteAcceptFlag": "虚拟站址",
        "deleteTime": null,
        "mobileSiteName": null,
        "unicomSiteName": "杭州涌金广场",
        "telecomSiteName": null,
        "isTransferTower": "否",
        "isTransferRoom": "否",
        "logOutReason": null,
        "anchorBusiness": "运营商业务类",
        "oneLevelBusiness": "市县乡",
        "twoLevelBusiness": "密集市区",
        "businessType": "运营商业务类",
        "businessSubclass": "宏站类",
        "sharedUnit": "联通",
        "baseStationCategory": null,
        "actualDemolitionDate": null,
        "currentSiteState": "正常",
        "sysDate": "2022-08-19T07:55:26.000Z"
    },
    {
        "city": "杭州市",
        "county": "上城区",
        "adminRegion": "杭州市",
        "organization": "中国铁塔股份有限公司杭州市分公司",
        "siteName": "杭州SJQ通信机房",
        "siteNum": "330106908000000260",
        "siteType": "楼面站",
        "longitude": 120.156331,
        "latitude": 30.233310999999997,
        "address": "浙江省杭州市西湖区南山路",
        "siteTopography": "平原",
        "accessDate": "2015-10-31T16:00:00.000Z",
        "originalPropertyUnit": "电信",
        "oneLevelStatus": "在网",
        "twoLevelStatus": "正常起租",
        "remark": "上站有难度,grade",
        "changeTime": "2021-07-30T09:37:29.000Z",
        "entryStaff": "adminres",
        "entryTime": "2015-03-11T16:00:00.000Z",
        "modifyMan": "luoyi",
        "isBlock": "否",
        "siteSource": "自有站",
        "sourceIndustry": "通信",
        "sourceChannel": "移交",
        "siteMergeRecord": null,
        "siteAcceptFlag": "虚拟站址",
        "deleteTime": null,
        "mobileSiteName": null,
        "unicomSiteName": "杭州省军区通信机房",
        "telecomSiteName": null,
        "isTransferTower": "否",
        "isTransferRoom": "否",
        "logOutReason": null,
        "anchorBusiness": "运营商业务类",
        "oneLevelBusiness": "市县乡",
        "twoLevelBusiness": "一般市区",
        "businessType": "运营商业务类",
        "businessSubclass": "宏站类",
        "sharedUnit": "电信,联通",
        "baseStationCategory": null,
        "actualDemolitionDate": null,
        "currentSiteState": "正常",
        "sysDate": "2022-08-19T07:55:26.000Z"
    },
    {
        "city": "杭州市",
        "county": "上城区",
        "adminRegion": "杭州市",
        "organization": "中国铁塔股份有限公司杭州市分公司",
        "siteName": "上城保利翡翠海岸7号楼NR",
        "siteNum": "330102500000001512",
        "siteType": "楼面站",
        "longitude": 120.19051999999999,
        "latitude": 30.24033,
        "address": "浙江省杭州市近江路与思潮巷交汇处滨江保利翡翠海岸七幢楼顶",
        "siteTopography": "平原",
        "accessDate": "2020-03-18T16:00:00.000Z",
        "originalPropertyUnit": "中国铁塔",
        "oneLevelStatus": "在网",
        "twoLevelStatus": "正常起租",
        "remark": null,
        "changeTime": "2021-08-31T09:11:35.000Z",
        "entryStaff": "fuyf3",
        "entryTime": "2019-08-06T08:39:00.000Z",
        "modifyMan": "luoyi",
        "isBlock": "否",
        "siteSource": "自有站",
        "sourceIndustry": "通信",
        "sourceChannel": "自建",
        "siteMergeRecord": null,
        "siteAcceptFlag": null,
        "deleteTime": null,
        "mobileSiteName": null,
        "unicomSiteName": null,
        "telecomSiteName": null,
        "isTransferTower": "否",
        "isTransferRoom": "否",
        "logOutReason": null,
        "anchorBusiness": "运营商业务类",
        "oneLevelBusiness": "市县乡",
        "twoLevelBusiness": "密集市区",
        "businessType": "运营商业务类",
        "businessSubclass": "宏站类",
        "sharedUnit": "移动",
        "baseStationCategory": null,
        "actualDemolitionDate": null,
        "currentSiteState": "正常",
        "sysDate": "2022-08-19T07:55:26.000Z"
    },
    {
        "city": "杭州市",
        "county": "上城区",
        "adminRegion": "杭州市",
        "organization": "中国铁塔股份有限公司杭州市分公司",
        "siteName": "杭州市上城印月宾馆",
        "siteNum": "330102500000001521",
        "siteType": "楼面站",
        "longitude": 120.17401,
        "latitude": 30.238601,
        "address": "杭州上城印月宾馆",
        "siteTopography": "平原",
        "accessDate": null,
        "originalPropertyUnit": "中国铁塔",
        "oneLevelStatus": "在网",
        "twoLevelStatus": "正常起租",
        "remark": null,
        "changeTime": "2022-03-31T07:50:06.000Z",
        "entryStaff": "chenqiao",
        "entryTime": "2019-12-11T02:51:02.000Z",
        "modifyMan": "luoyi",
        "isBlock": "否",
        "siteSource": "自有站",
        "sourceIndustry": "通信",
        "sourceChannel": "自建",
        "siteMergeRecord": null,
        "siteAcceptFlag": null,
        "deleteTime": null,
        "mobileSiteName": null,
        "unicomSiteName": null,
        "telecomSiteName": null,
        "isTransferTower": "否",
        "isTransferRoom": "否",
        "logOutReason": null,
        "anchorBusiness": "运营商业务类",
        "oneLevelBusiness": "市县乡",
        "twoLevelBusiness": "密集市区",
        "businessType": "运营商业务类",
        "businessSubclass": "宏站类",
        "sharedUnit": "电信",
        "baseStationCategory": null,
        "actualDemolitionDate": null,
        "currentSiteState": "正常",
        "sysDate": "2022-08-19T07:55:26.000Z"
    },
    {
        "city": "杭州市",
        "county": "上城区",
        "adminRegion": "杭州市",
        "organization": "中国铁塔股份有限公司杭州市分公司",
        "siteName": "杭州上城机动车服务管理局",
        "siteNum": "330127700000054892",
        "siteType": "楼面站",
        "longitude": 120.179751,
        "latitude": 30.221940999999998,
        "address": "杭州市淳安县威坪镇徐家坞村附近山坡上",
        "siteTopography": "平原",
        "accessDate": "2015-11-29T16:00:00.000Z",
        "originalPropertyUnit": "电信",
        "oneLevelStatus": "在网",
        "twoLevelStatus": "正常起租",
        "remark": ",grade",
        "changeTime": "2020-04-20T15:50:10.000Z",
        "entryStaff": "luoyi",
        "entryTime": "2015-06-09T06:45:27.000Z",
        "modifyMan": "luoyi",
        "isBlock": "否",
        "siteSource": "自有站",
        "sourceIndustry": "通信",
        "sourceChannel": "移交",
        "siteMergeRecord": null,
        "siteAcceptFlag": "是",
        "deleteTime": null,
        "mobileSiteName": null,
        "unicomSiteName": null,
        "telecomSiteName": null,
        "isTransferTower": "否",
        "isTransferRoom": "否",
        "logOutReason": null,
        "anchorBusiness": "运营商业务类",
        "oneLevelBusiness": "市县乡",
        "twoLevelBusiness": "一般市区",
        "businessType": "运营商业务类",
        "businessSubclass": "宏站类",
        "sharedUnit": "电信",
        "baseStationCategory": null,
        "actualDemolitionDate": null,
        "currentSiteState": "正常",
        "sysDate": "2022-08-19T07:55:26.000Z"
    },
    {
        "city": "杭州市",
        "county": "上城区",
        "adminRegion": "杭州市",
        "organization": "中国铁塔股份有限公司杭州市分公司",
        "siteName": "二公园码头",
        "siteNum": "330106500000002104",
        "siteType": "微站",
        "longitude": 120.15471600000001,
        "latitude": 30.258764,
        "address": "二公园码头",
        "siteTopography": "平原",
        "accessDate": "2018-12-28T16:00:00.000Z",
        "originalPropertyUnit": "中国铁塔",
        "oneLevelStatus": "在网",
        "twoLevelStatus": "正常起租",
        "remark": null,
        "changeTime": "2019-01-10T03:25:05.000Z",
        "entryStaff": "zhugd",
        "entryTime": "2018-09-29T13:28:00.000Z",
        "modifyMan": "luoyi",
        "isBlock": "否",
        "siteSource": "自有站",
        "sourceIndustry": "通信",
        "sourceChannel": "自建",
        "siteMergeRecord": null,
        "siteAcceptFlag": "是",
        "deleteTime": null,
        "mobileSiteName": null,
        "unicomSiteName": null,
        "telecomSiteName": null,
        "isTransferTower": "否",
        "isTransferRoom": "否",
        "logOutReason": null,
        "anchorBusiness": "运营商业务类",
        "oneLevelBusiness": "景区",
        "twoLevelBusiness": "3A级景区",
        "businessType": "运营商业务类",
        "businessSubclass": "微站类",
        "sharedUnit": "移动,电信",
        "baseStationCategory": null,
        "actualDemolitionDate": null,
        "currentSiteState": "正常",
        "sysDate": "2022-08-19T07:55:26.000Z"
    },
    {
        "city": "杭州市",
        "county": "上城区",
        "adminRegion": "杭州市",
        "organization": "中国铁塔股份有限公司杭州市分公司",
        "siteName": "杭州西湖花苑",
        "siteNum": "330103908000000366",
        "siteType": "楼面站",
        "longitude": 120.153741,
        "latitude": 30.26336,
        "address": "浙江省杭州市上城区换成西路18号杭州西湖花苑基站",
        "siteTopography": "平原",
        "accessDate": "2021-05-12T12:51:02.000Z",
        "originalPropertyUnit": "联通",
        "oneLevelStatus": "在网",
        "twoLevelStatus": "正常起租",
        "remark": "7e09fb56159111e59893fa163e7246ea,grade",
        "changeTime": "2020-04-20T15:54:07.000Z",
        "entryStaff": "adminres",
        "entryTime": "2015-03-11T16:00:00.000Z",
        "modifyMan": "luoyi",
        "isBlock": "否",
        "siteSource": "自有站",
        "sourceIndustry": "通信",
        "sourceChannel": "移交",
        "siteMergeRecord": null,
        "siteAcceptFlag": null,
        "deleteTime": null,
        "mobileSiteName": null,
        "unicomSiteName": "杭州西湖花苑",
        "telecomSiteName": null,
        "isTransferTower": "否",
        "isTransferRoom": "否",
        "logOutReason": null,
        "anchorBusiness": "运营商业务类",
        "oneLevelBusiness": "公共场所",
        "twoLevelBusiness": "住宅小区",
        "businessType": "运营商业务类",
        "businessSubclass": "宏站类",
        "sharedUnit": "联通",
        "baseStationCategory": null,
        "actualDemolitionDate": null,
        "currentSiteState": "正常",
        "sysDate": "2022-08-19T07:55:26.000Z"
    },
    {
        "city": "杭州市",
        "county": "上城区",
        "adminRegion": "杭州市",
        "organization": "中国铁塔股份有限公司杭州市分公司",
        "siteName": "上城万松书院后门NR",
        "siteNum": "330106500000002367",
        "siteType": "地面站",
        "longitude": 120.15635499999999,
        "latitude": 30.227774,
        "address": "浙江省杭州市西湖区玉皇山路77号杭师大音乐学院图书馆南面山坡",
        "siteTopography": "平原",
        "accessDate": "2014-12-31T16:00:00.000Z",
        "originalPropertyUnit": "中国铁塔",
        "oneLevelStatus": "在网",
        "twoLevelStatus": "正常起租",
        "remark": null,
        "changeTime": "2022-07-29T15:13:44.000Z",
        "entryStaff": "chenqiao",
        "entryTime": "2019-07-23T07:01:30.000Z",
        "modifyMan": "wanghui",
        "isBlock": "否",
        "siteSource": "自有站",
        "sourceIndustry": "通信",
        "sourceChannel": "自建",
        "siteMergeRecord": null,
        "siteAcceptFlag": null,
        "deleteTime": null,
        "mobileSiteName": null,
        "unicomSiteName": null,
        "telecomSiteName": null,
        "isTransferTower": "否",
        "isTransferRoom": "否",
        "logOutReason": null,
        "anchorBusiness": "运营商业务类",
        "oneLevelBusiness": "景区",
        "twoLevelBusiness": "4A级景区",
        "businessType": "运营商业务类",
        "businessSubclass": "宏站类",
        "sharedUnit": "移动",
        "baseStationCategory": null,
        "actualDemolitionDate": null,
        "currentSiteState": "正常",
        "sysDate": "2022-08-19T07:55:26.000Z"
    },
    {
        "city": "杭州市",
        "county": "上城区",
        "adminRegion": "杭州市",
        "organization": "中国铁塔股份有限公司杭州市分公司",
        "siteName": "杭州玉皇山庄",
        "siteNum": "330106908000000549",
        "siteType": "楼面站",
        "longitude": 120.149124,
        "latitude": 30.226613,
        "address": "浙江省杭州市上城区玉皇山路74号玉皇山庄",
        "siteTopography": "平原",
        "accessDate": "2015-10-31T16:00:00.000Z",
        "originalPropertyUnit": "电信",
        "oneLevelStatus": "在网",
        "twoLevelStatus": "正常起租",
        "remark": "aa4b3624159111e59893fa163e7246ea,grade",
        "changeTime": "2020-04-20T15:44:39.000Z",
        "entryStaff": "adminres",
        "entryTime": "2015-03-11T16:00:00.000Z",
        "modifyMan": "luoyi",
        "isBlock": "否",
        "siteSource": "自有站",
        "sourceIndustry": "通信",
        "sourceChannel": "移交",
        "siteMergeRecord": "330106904000023651",
        "siteAcceptFlag": "虚拟站址",
        "deleteTime": null,
        "mobileSiteName": null,
        "unicomSiteName": null,
        "telecomSiteName": "杭州玉皇山庄",
        "isTransferTower": "否",
        "isTransferRoom": "否",
        "logOutReason": null,
        "anchorBusiness": "运营商业务类",
        "oneLevelBusiness": "景区",
        "twoLevelBusiness": "3A级景区",
        "businessType": "运营商业务类",
        "businessSubclass": "宏站类",
        "sharedUnit": "电信,联通",
        "baseStationCategory": "1",
        "actualDemolitionDate": null,
        "currentSiteState": "正常",
        "sysDate": "2022-08-19T07:55:26.000Z"
    }],
    "count": 101082
}
